# Generated by Django 2.2.4 on 2019-08-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190821_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
