# Generated by Django 2.2.4 on 2019-08-22 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190822_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='myusers',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
