# Generated by Django 2.2.4 on 2019-08-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190822_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUsers',
        ),
    ]
