# Generated by Django 2.2.4 on 2019-08-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
